site_name: skimindex
docs_dir: docsmd
site_dir: docs

nav:
  - Home: index.md
  - Directory Structure: directory-structure.md
  - Configuration Format: config-format.md
  - Environment Variables: environment-variables.md
  - Data Model: data.md
  - Processing Model: processing.md
  - Entry Point (skimindex.sh): entrypoint.md
  - Pipeline Commands: commands.md
  - Writing Shell Commands: devshell.md
  - Tools: tools.md

theme:
  name: readthedocs
