#!/usr/bin/env bash
# =============================================================================
# skimindex — pipeline entry point
#
# Usage:
#   skimindex [--project-dir DIR] <subcommand> [subcommand-options]
#
# Global options:
#   --project-dir DIR    Project root directory (default: current working
#                        directory).  All relative paths in the configuration
#                        are resolved from this directory.
#   --local              Use the locally cached image without checking the
#                        registry for updates (docker/podman only; apptainer
#                        always uses the local SIF file).
#   -h, --help           Show this help and exit.
#
# Subcommands:
#   init                     Initialise a new project directory and download the default config.
#   update                   Pull the latest container image from the registry (or refresh the SIF for apptainer).
#   shell                    Start an interactive shell inside the container.
#   decontam                 Prepare decontamination filter data.
#   download                 Download GenBank and reference genome data.
#   validate                 Validate the skimindex configuration file.
#
# shell options:
#   --mount SRC:DST      Bind-mount SRC (host) to DST (container).
#                        May be repeated for multiple extra mounts.
#
# Configuration:
#   <project-dir>/config/skimindex.toml
#       Pipeline configuration.  The [local_directories] section maps each
#       key k to a host path that is bind-mounted to /k inside the container.
#
# Container runtime:
#   Auto-detected in priority order: apptainer > docker > podman.
#   Apptainer uses the local SIF image:
#       <project-dir>/images/skimindex-latest.sif
#   Docker / Podman pull the image from the registry on first use:
#       registry.metabarcoding.org/arcecogen/skimindex:latest
# =============================================================================
# NOTE: Do not edit this file directly.
#       It is generated from docker/skimindex.sh.in by docker/build_user_script.sh.
#       Edit the template and regenerate instead.
set -euo pipefail

# =============================================================================
# Inlined utility functions
# =============================================================================
# ============================================================
# __skimindex_log.sh
# Logging facilities for skimindex bash scripts.
#
# Provides:
#   logdebug / loginfo / logwarning / logerror <MESSAGE>
#   setloglevel <LEVEL>          (DEBUG | INFO | WARNING | ERROR)
#   openlogfile <PATH> [MIRROR] [EVERYTHING]
#   closelogfile
#
# All logging goes through file descriptor 3 (default: stderr).
# VT100 colours are applied on terminals; stripped when writing to files.
# Default level: INFO.
#
# Source this file — do NOT execute it directly.
# ============================================================



_SKIMINDEX_LOG_LOADED=1

LOG_DEBUG_LEVEL=1
LOG_INFO_LEVEL=2
LOG_WARNING_LEVEL=3
LOG_ERROR_LEVEL=4

LOG_LEVEL=$LOG_INFO_LEVEL

exec 3>&2

# ---------- VT100 colour codes ----------
_LOG_RESET=$'\033[0m'
_LOG_CYAN=$'\033[0;36m'    # DEBUG
_LOG_GREEN=$'\033[0;32m'   # INFO
_LOG_YELLOW=$'\033[0;33m'  # WARNING
_LOG_RED=$'\033[1;31m'     # ERROR
_LOG_DIM=$'\033[2m'        # timestamp / host dimmed

# ---------- internal formatter ----------

_logwrite() {
    local color="$1"
    local label="$2"
    shift 2
    printf '%s%s%s %s%-9s%s %s%s.%s%s -- %s\n' \
        "${_LOG_DIM}" "$(date +'%Y-%m-%d %H:%M:%S')" "${_LOG_RESET}" \
        "${color}" "${label}" "${_LOG_RESET}" \
        "${_LOG_DIM}" "$(hostname)" "$$" "${_LOG_RESET}" \
        "$*" 1>&3
}

# ---------- public log functions ----------

function logdebug() {
    (( LOG_LEVEL <= LOG_DEBUG_LEVEL )) && \
        _logwrite "${_LOG_CYAN}"   "[DEBUG  ]" "$@"
    return 0
}

function loginfo() {
    (( LOG_LEVEL <= LOG_INFO_LEVEL )) && \
        _logwrite "${_LOG_GREEN}"  "[INFO   ]" "$@"
    return 0
}

function logwarning() {
    (( LOG_LEVEL <= LOG_WARNING_LEVEL )) && \
        _logwrite "${_LOG_YELLOW}" "[WARNING]" "$@"
    return 0
}

function logerror() {
    (( LOG_LEVEL <= LOG_ERROR_LEVEL )) && \
        _logwrite "${_LOG_RED}"    "[ERROR  ]" "$@"
    return 0
}

function setloglevel() {
    local _varname="LOG_${1}_LEVEL"
    LOG_LEVEL="${!_varname}"
    loginfo "Logging level set to: ${1} (${LOG_LEVEL})"
}

# ---------- logfile management ----------

function openlogfile() {
    local logpath="$1"
    local mirror="${2:-false}"      # "true" → tee logs to screen + file
    local everything="${3:-false}"  # "true" → also redirect fd 2 through fd 3
    if ! touch "$logpath" 2>/dev/null; then
        logwarning "cannot open log file: $logpath — logging to stderr only."
        return 0
    fi
    if [[ "$mirror" == "true" ]]; then
        exec 3> >(tee >(sed 's/\x1b\[[0-9;]*m//g' >> "$logpath") >&2)
    else
        exec 3> >(sed 's/\x1b\[[0-9;]*m//g' >> "$logpath")
    fi
    if [[ "$everything" == "true" ]]; then
        exec 2>&3
        LOGEVERYTHING=1
    fi
    LOGFILE="$logpath"
}

function closelogfile() {
    if [[ -n "${LOGFILE:-}" ]]; then
        if [[ -n "${LOGEVERYTHING:-}" ]]; then
            exec 2>/dev/tty 2>/dev/null || exec 2>&1
            unset LOGEVERYTHING
        fi
        exec 3>&-
        exec 3>&2
        LOGFILE=""
    fi
}

# =============================================================================
# Image identity  (substituted at build time by docker/build_user_script.sh)
# =============================================================================
_SKI_IMAGE_REGISTRY="registry.metabarcoding.org/arcecogen"
_SKI_IMAGE_NAME="skimindex"
_SKI_IMAGE_TAG="latest"

# URL of the raw skimindex.toml in the source repository (used by `init`).
_SKI_CONFIG_URL="https://raw.githubusercontent.com/metabarcoding/skimindex/main/config/skimindex.toml"

# =============================================================================
# Project root — defaults to current working directory
# =============================================================================
PROJECT_ROOT="$PWD"
_SKI_LOCAL=0   # set to 1 by --local; disables --pull always for docker/podman

# =============================================================================
# Subcommand help
# =============================================================================
_ski_help() {
    # Build extra lines for user-defined subcommands from ${PROJECT_ROOT}/usercmd/
    local _usercmd_dir="${PROJECT_ROOT}/usercmd"
    local _extra=""
    if [[ -d "$_usercmd_dir" ]] && compgen -G "${_usercmd_dir}/*.sh" >/dev/null 2>&1; then
        for _f in "${_usercmd_dir}"/*.sh; do
            _name="$(basename "$_f" .sh)"
            _desc="$(awk '
                NR==1 { next }
                /^# *[-=]{4,}/ { next }
                /^#/ { sub(/^# */, ""); print; exit }
            ' "$_f")"
            _extra+="$(printf '  %-25s %s\n' "$_name" "${_desc:-(no description)}")"$'\n'
        done
    fi
    # Extract the header comment and splice usercmd lines before "shell options:"
    export _SKI_HELP_EXTRA="$_extra"
    sed -En '2,/^# =+$/{ s/^# ?//; /^=+$/d; p; }' "$0" \
        | awk '
            /^shell options:/ && ENVIRON["_SKI_HELP_EXTRA"] != "" {
                printf "User subcommands:\n%s\n", ENVIRON["_SKI_HELP_EXTRA"]
            }
            { print }
        '
}

# Parse global options before the subcommand.
# Stop option processing at the first non-option argument (the subcommand)
# so that options belonging to the subcommand (e.g. --help) are not consumed.
_remaining_args=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --project-dir)
            mkdir -p "$2"
            PROJECT_ROOT="$(cd "$2" && pwd)"; shift 2 ;;
        --project-dir=*)
            mkdir -p "${1#--project-dir=}"
            PROJECT_ROOT="$(cd "${1#--project-dir=}" && pwd)"; shift ;;
        --local)
            _SKI_LOCAL=1; shift ;;
        -h|--help)
            _ski_help
            exit 0 ;;
        --)
            shift; _remaining_args+=("$@"); break ;;
        -*)
            logerror "Unknown global option: $1"
            logerror "Run '$(basename "$0") --help' for usage."
            exit 1 ;;
        *)
            # First non-option arg is the subcommand — stop global parsing
            _remaining_args+=("$@"); break ;;
    esac
done
set -- "${_remaining_args[@]+"${_remaining_args[@]}"}"

CONFIG_FILE="${PROJECT_ROOT}/config/skimindex.toml"
SIF_FILE="${PROJECT_ROOT}/images/${_SKI_IMAGE_NAME}-${_SKI_IMAGE_TAG}.sif"

# =============================================================================
# Runtime detection
# =============================================================================
_ski_detect_runtime() {
    if   command -v apptainer >/dev/null 2>&1; then echo apptainer
    elif command -v docker    >/dev/null 2>&1; then echo docker
    elif command -v podman    >/dev/null 2>&1; then echo podman
    else echo none
    fi
}

RUNTIME="$(_ski_detect_runtime)"

# =============================================================================
# Config-driven bind-mount and host-dir helpers
# =============================================================================

_ski_host_dirs() {
    [[ -f "$CONFIG_FILE" ]] || return 0
    awk -v root="$PROJECT_ROOT" '
        /^\[local_directories\]/ { s=1; next }
        /^\[/                    { s=0 }
        s && /^[a-zA-Z_][a-zA-Z0-9_]*[[:space:]]*=/ {
            v=$0; gsub(/^[^"]*"/, "", v); gsub(/".*$/, "", v)
            print (substr(v,1,1)=="/") ? v : root "/" v
        }
    ' "$CONFIG_FILE"
}

_ski_bind_flags() {
    local prefix="$1"
    [[ -f "$CONFIG_FILE" ]] || return 0
    awk -v root="$PROJECT_ROOT" -v pfx="$prefix" '
        /^\[local_directories\]/ { s=1; next }
        /^\[/                    { s=0 }
        s && /^[a-zA-Z_][a-zA-Z0-9_]*[[:space:]]*=/ {
            k=$1
            v=$0; gsub(/^[^"]*"/, "", v); gsub(/".*$/, "", v)
            path = (substr(v,1,1)=="/") ? v : root "/" v
            printf "%s\n%s:/%s\n", pfx, path, k
        }
    ' "$CONFIG_FILE"
}

_ski_build_bind_array() {
    local prefix="$1" flag
    while IFS= read -r flag; do
        BIND+=("$flag")
    done < <(_ski_bind_flags "$prefix")
}

# =============================================================================
# Directory management
# =============================================================================
_ski_ensure_dirs() {
    local dir
    while IFS= read -r dir; do
        mkdir -p "$dir"
    done < <(_ski_host_dirs)
}

# =============================================================================
# Run helpers
# =============================================================================

# _ski_docker_needs_update
#   Returns 0 (true) when the registry digest differs from the local image digest,
#   or when the image is not present locally.  Returns 1 when up-to-date or
#   when the registry cannot be reached (offline mode).
_ski_docker_needs_update() {
    local _SKI_FULL_IMAGE="${_SKI_IMAGE_REGISTRY}/${_SKI_IMAGE_NAME}:${_SKI_IMAGE_TAG}"
    # If the image is not present locally, we need to pull it
    if ! "$RUNTIME" image inspect "$_SKI_FULL_IMAGE" >/dev/null 2>&1; then
        return 0
    fi
    local remote_digest local_digest
    remote_digest=$(_ski_registry_digest \
        "$_SKI_IMAGE_REGISTRY" "$_SKI_IMAGE_NAME" "$_SKI_IMAGE_TAG")
    [[ -z "$remote_digest" ]] && return 1   # offline / unreachable → skip
    local_digest=$("$RUNTIME" image inspect --format '{{index .RepoDigests 0}}' \
        "$_SKI_FULL_IMAGE" 2>/dev/null | grep -o 'sha256:[^@]*' || true)
    [[ "$remote_digest" != "$local_digest" ]]
}

# _ski_ensure_current
#   Apptainer: update SIF when digest differs or SIF is absent.
#   Docker/podman: compare registry digest first; pull with live output only
#                  when an update is actually needed.  Silent when up-to-date.
#   Skipped with --local.
_ski_ensure_current() {
    (( _SKI_LOCAL )) && return 0
    local _SKI_FULL_IMAGE="${_SKI_IMAGE_REGISTRY}/${_SKI_IMAGE_NAME}:${_SKI_IMAGE_TAG}"
    if [[ "$RUNTIME" == "apptainer" ]]; then
        _ski_apptainer_needs_update && _ski_update
    else
        if _ski_docker_needs_update; then
            loginfo "Pulling updated image: ${_SKI_FULL_IMAGE}"
            "$RUNTIME" pull "$_SKI_FULL_IMAGE"
        fi
    fi
    return 0
}

# _ski_run_interactive [extra_mount ...]
#   extra_mount: "src:dst" pairs added on top of the config-driven mounts.
_ski_run_interactive() {
    _ski_ensure_dirs
    _ski_ensure_current
    local _SKI_FULL_IMAGE="${_SKI_IMAGE_REGISTRY}/${_SKI_IMAGE_NAME}:${_SKI_IMAGE_TAG}"
    local BIND=()
    local _shell_init=/app/scripts/__ski_shell_init.sh
    if [[ "$RUNTIME" == "apptainer" ]]; then
        _ski_build_bind_array "--bind"
        for _m in "$@"; do BIND+=(--bind "$_m"); done
        APPTAINERENV_PREPEND_PATH=/app/bin:/app/scripts \
        apptainer exec --pwd /app "${BIND[@]}" "$SIF_FILE" \
            bash --init-file "$_shell_init"
    else
        _ski_build_bind_array "-v"
        for _m in "$@"; do BIND+=(-v "$_m"); done
        "$RUNTIME" run --rm -it "${BIND[@]}" "$_SKI_FULL_IMAGE" \
            bash --init-file "$_shell_init"
    fi
}

_ski_run_exec() {
    _ski_ensure_dirs
    _ski_ensure_current
    local _SKI_FULL_IMAGE="${_SKI_IMAGE_REGISTRY}/${_SKI_IMAGE_NAME}:${_SKI_IMAGE_TAG}"
    local BIND=()
    if [[ "$RUNTIME" == "apptainer" ]]; then
        _ski_build_bind_array "--bind"
        APPTAINERENV_PREPEND_PATH=/app/bin:/app/scripts \
        apptainer exec --pwd /app "${BIND[@]}" "$SIF_FILE" "$@"
    else
        _ski_build_bind_array "-v"
        "$RUNTIME" run --rm "${BIND[@]}" "$_SKI_FULL_IMAGE" "$@"
    fi
}

# =============================================================================
# update subcommand — pull the latest image
# =============================================================================

# _ski_registry_digest <registry> <name> <tag>
#   Query the OCI registry for the current digest of <name>:<tag>.
#   Tries both OCI and Docker v2 manifest media types.
#   Outputs the digest (sha256:…) on success, empty string on failure.
_ski_registry_digest() {
    local registry="$1" name="$2" tag="$3"
    # registry may contain an org path (e.g. registry.example.com/org).
    # The OCI distribution v2 API requires /v2/ immediately after the host,
    # so split registry into host and optional org prefix.
    local host="${registry%%/*}"
    local prefix="${registry#"$host"}"           # empty or /org[/...]
    local repo="${prefix:+${prefix#/}/}${name}"  # org/name  or just  name
    local url="https://${host}/v2/${repo}/manifests/${tag}"
    local digest=""
    if command -v curl >/dev/null 2>&1; then
        # Fetch the manifest index and extract the digest for the current
        # platform (linux/<arch>).  This avoids false positives when only
        # a different architecture's image is updated.
        local arch
        case "$(uname -m)" in
            x86_64)  arch="amd64" ;;
            aarch64) arch="arm64" ;;
            *)       arch="$(uname -m)" ;;
        esac
        local body
        body=$(curl -fsSL --connect-timeout 5 \
            -H "Accept: application/vnd.oci.image.index.v1+json" \
            -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json" \
            "$url" 2>/dev/null)
        # Parse the platform-specific digest from the JSON index.
        # digest appears before architecture in each manifest entry, so we
        # record the last seen digest and print it when the arch matches.
        # Falls back to empty string if the response is not a manifest list.
        digest=$(printf '%s' "$body" \
            | awk -v arch="$arch" \
                '/"digest":/ { match($0, /sha256:[^"]+/); last = substr($0, RSTART, RLENGTH) }
                 /"architecture":/ && index($0, "\"" arch "\"") > 0 && length(last) > 0 { print last; last = "" }')
    fi
    printf '%s' "$digest"
}

# _ski_apptainer_needs_update
#   Returns 0 (true) when the registry digest differs from the locally cached
#   digest, or when the SIF file is absent.  Returns 1 when up-to-date or
#   when the registry cannot be reached (offline mode).
_ski_apptainer_needs_update() {
    local digest_file="${SIF_FILE%.sif}.digest"
    [[ -f "$SIF_FILE" ]] || return 0   # no SIF → must pull

    local remote_digest
    remote_digest=$(_ski_registry_digest \
        "$_SKI_IMAGE_REGISTRY" "$_SKI_IMAGE_NAME" "$_SKI_IMAGE_TAG")
    [[ -z "$remote_digest" ]] && return 1   # offline / unreachable → skip

    local local_digest=""
    [[ -f "$digest_file" ]] && local_digest="$(cat "$digest_file")"

    [[ "$remote_digest" != "$local_digest" ]]
}

_ski_update() {
    local _SKI_FULL_IMAGE="${_SKI_IMAGE_REGISTRY}/${_SKI_IMAGE_NAME}:${_SKI_IMAGE_TAG}"
    if [[ "$RUNTIME" == "apptainer" ]]; then
        local sif_dir digest_file
        sif_dir="$(dirname "$SIF_FILE")"
        digest_file="${SIF_FILE%.sif}.digest"
        mkdir -p "$sif_dir"
        loginfo "Pulling latest SIF from docker://${_SKI_FULL_IMAGE}"
        loginfo "Destination: $SIF_FILE"
        apptainer pull --force "$SIF_FILE" "docker://${_SKI_FULL_IMAGE}"
        # Record the remote digest so future checks can skip unnecessary pulls
        local remote_digest
        remote_digest=$(_ski_registry_digest \
            "$_SKI_IMAGE_REGISTRY" "$_SKI_IMAGE_NAME" "$_SKI_IMAGE_TAG")
        [[ -n "$remote_digest" ]] && printf '%s' "$remote_digest" > "$digest_file"
        loginfo "SIF updated: $SIF_FILE"
    else
        loginfo "Pulling latest image: ${_SKI_FULL_IMAGE}"
        "$RUNTIME" pull "$_SKI_FULL_IMAGE"
        loginfo "Image updated."
    fi
}

# =============================================================================
# init subcommand
# =============================================================================
_ski_init() {
    loginfo "Initialising project directory: $PROJECT_ROOT"

    mkdir -p "${PROJECT_ROOT}/config"
    loginfo "Directory ready: ${PROJECT_ROOT}/config"

    if [[ -f "$CONFIG_FILE" ]]; then
        loginfo "Config already present: $CONFIG_FILE — skipping download."
    else
        loginfo "Downloading config from: $_SKI_CONFIG_URL"
        if command -v curl >/dev/null 2>&1; then
            curl -fsSL "$_SKI_CONFIG_URL" -o "$CONFIG_FILE"
        elif command -v wget >/dev/null 2>&1; then
            wget -q "$_SKI_CONFIG_URL" -O "$CONFIG_FILE"
        else
            logerror "Neither curl nor wget found — cannot download config."
            exit 1
        fi
        loginfo "Config written: $CONFIG_FILE"
    fi

    local dir
    while IFS= read -r dir; do
        mkdir -p "$dir"
        loginfo "Directory ready: $dir"
    done < <(_ski_host_dirs)

    loginfo "Project initialised successfully."
    loginfo "Edit $CONFIG_FILE to customise paths and downloads."
}

# =============================================================================
# Subcommand dispatch
# =============================================================================

if [[ $# -eq 0 ]]; then
    _ski_help
    exit 0
fi

SUBCMD="$1"; shift

case "$SUBCMD" in
    -h|--help)
        _ski_help
        exit 0
        ;;
    init)
        _ski_init "$@"
        exit 0
        ;;
    update)
        if [[ "$RUNTIME" == "none" ]]; then
            logerror "No container runtime found (apptainer, docker or podman required)."
            exit 1
        fi
        _ski_update
        exit 0
        ;;
    shell)
        if [[ "$RUNTIME" == "none" ]]; then

            logerror "No container runtime found (apptainer, docker or podman required)."
            exit 1
        fi
        _shell_mounts=()
        while [[ $# -gt 0 ]]; do
            case "$1" in
                --mount)     _shell_mounts+=("$2"); shift 2 ;;
                --mount=*)   _shell_mounts+=("${1#--mount=}"); shift ;;
                --)          shift; break ;;
                -*)          logerror "Unknown shell option: $1"; exit 1 ;;
                *)           break ;;
            esac
        done
        _ski_run_interactive "${_shell_mounts[@]}"
        exit 0
        ;;
esac

# All remaining subcommands require a container runtime
if [[ "$RUNTIME" == "none" ]]; then
    logerror "No container runtime found (apptainer, docker or podman required)."
    exit 1
fi

case "$SUBCMD" in
    decontam)
        _ski_run_exec decontam "$@"
        ;;
    download)
        _ski_run_exec download "$@"
        ;;
    validate)
        _ski_run_exec validate "$@"
        ;;
    *)
        # Dynamic lookup in ${PROJECT_ROOT}/usercmd/ — run inside the container
        # with /usercmd bind-mounted, so scripts can source /app/scripts libs.
        if [[ -f "${PROJECT_ROOT}/usercmd/${SUBCMD}.sh" ]]; then
            _ski_run_exec env SKIMINDEX_SCRIPTS_DIR=/app/scripts bash "/usercmd/${SUBCMD}.sh" "$@"
        else
            logerror "Unknown subcommand '$SUBCMD'."
            logerror "Run '$(basename "$0") --help' for usage."
            exit 1
        fi
        ;;
esac
